[project]
name = "GO-Diff"
dynamic = ["version"]
description = "GO-Diff"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "torch",
    "lightning",
    "torch_geometric",
    "tensorboard",
    "numpy",
    "ase",
    "rich-click",
    "AGeDi[full] >= 1.0.0",
    "matplotlib",
    "seaborn",
    "pandas",
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "VERSION"
pattern = "(?P<version>.+)"

[tool.ruff]
line-length = 88

[tool.pytest.ini_options]
testpaths = ["tests"]
