[project]
name = "GO-Diff"
version = "0.0.1"
description = "GO-Diff"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "torch",
    "lightning",
    "torch_geometric",
    "torch-ema",
    "tensorboard",
    "numpy",
    "ase",
    "rich-click",
    "schnetpack",
    "AGeDi",
    "matplotlib",
    "seaborn",
    "pandas",
]

[project.optional-dependencies]
test = [
    "pytest>=7.0.1",
    "pytest-cov>=5.0.0",
]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 88

[tool.pytest.ini_options]
testpaths = ["tests"]
